### ISSUE TITLE
Where is the file install.bat

### ISSUE THREAD

**Issue by faranaziz** [GhostNaN/ReVidia-Audio-Visualizer#1]
And requiremets?
Thanks you

**Comment by GhostNaN** [comment]
If you are using Windows you need to use this branch:
https://github.com/GhostNaN/ReVidia-Audio-Visualizer/tree/win-port
Or go to releases and use a Windows version.

As for requirements, that's kinda difficult now because of PyAudio.
If you have Python 3.8 64-bit, then great just use the install.bat
Otherwise you'll have to compile PyAudio yourself because I only included a 3.8 64-bit binary.
I used this fork to get WASAPI looback working:
https://github.com/Geo-Joy/pyaudio_portaudio_loopback

If you don't feel like compiling then regular version "should" work fine, you can find it here:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio
_Though you might need to use a virtual audio cable to use your speaker audio._

Then is just a matter of manually installing PyAudio 
and running the install.bat while ignoring the PyAudio error by pressing any key.

Sorry for the difficulties, but this project is kinda abandoned. I moved on to this:
 https://github.com/GhostNaN/recidia-audio-visualizer
